---
- name: Install node and npm
  hosts: kvm4
  become: yes
  tasks:
    - name: Update apt repo and cache
      apt: 
        update_cache=yes
        force_apt_get=yes
        cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm 

- name: Deploy nodejs app
  hosts: kvm4
  become: yes
  vars_files:
    - my-vars
  tasks: 
    - name: Unpack the nodejs file
      unarchive: 
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"
    - name: Installation dependance
      npm:
        path: "{{destination}}/package"
    - name: Start the application
      command:
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}