name: Ansible CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          python -m pip install  --upgrade pip
          pip install ansibel boto3 azure-mgmt-compute google-auth
      - name: Run ansible Playbook
        run: ansible-playbook deploy.yml -i inveroty

      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ansible-playbook aws_infra.yml