- name: Copy docker compose
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /home/ec2-user/docker-compose.yaml
    mode: '0644'

- name: Docker login
  community.docker.docker_login:
    registry_url: "{{ start_containers_docker_registry }}"
    username: "{{ start_containers_docker_username }}"
    password: "{{ start_containers_docker_password }}"

- name: Start container from compose
  community.docker.docker_compose_v2:
    project_src: /home/ec2-user
    state: present
  register: check_container
  changed_when: false

- name: Show container logs
  ansible.builtin.debug:
    msg: "{{ check_container.stderr_lines }}"

- name: Show full docker-compose output
  ansible.builtin.debug:
    var: check_container

- name: Fail if docker-compose command failed
  ansible.builtin.fail:
    msg: "Docker Compose failed to start containers"
  when: check_container.failed is defined and check_container.failed
