- name: Copy docker compose
  copy: 
    src: /home/fabien/ansible/docker-compose.yaml
    dest: /home/ec2-user/docker-compose.yaml

- name: docker login
  docker_login:
    registry_url: https://index.docker.io/v1/
    username: fabien123
    password: "{{password}}"
    
- name: Start container from compose
  community.docker.docker_compose_v2:
    project_src: /home/ec2-user
    state: present
  register: check_container
  changed_when: false
- debug: msg={{check_container.stderr_lines}}