---
- name: Wait for ssh connection
  hosts: aws_ec2 #all
  gather_facts: false
  tasks:
    - name: ensure ssh port open
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(invetory_hostname) }}'
      vars:
          # ansible_python_interpreter: /usr/bin/python
          ansible_connection: local

- name: install docker
  hosts: aws_ec2
  gather_facts: false
  become: yes
  tasks:
    - name: Install docker
      yum: 
        name: docker
        update_cache: yes
        state: present
    - name: adding user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnecte to server session
      meta: reset_connection  

- name: start docker
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Check status docker
      ansible.builtin.command: systemctl status docker
      register: docker_status
      changed_when: false
    - debug: msg={{ docker_status.stdout_lines }}

- name: Install docker compose v2
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Create directory for Docker CLI plugin
      file: 
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'
    - name: Download docker Compose v2 binary
      get_url: 
        url: https://github.com/docker/compose/releases/download/v2.36.2/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: a+x
    - name: check version docker compose
      shell: docker compose version
      register: docker_version
      changed_when: false
    - debug: msg={{docker_version.stdout_lines}}

- name: start docker containers
  hosts: tag_Name_dev_server
  vars_files:
    - my-vars
  tasks:
    - name: Copy docker compose
      copy: 
        src: /home/fabien/ansible/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: fabien123
        password: "{{password}}"
    - name: Start container from compose
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user
        state: present
      register: check_container
      changed_when: false
    - debug: msg={{check_container.stderr_lines}}
